### PR TITLE
Suppor django 2.0+ new authenticate() api

### PR DESCRIPTION
**Pull request by glowka**

### CODE REVIEW

**Comment by Zeioth** [comment]
Thank you for your contribution. Travis seems to be failing with python 3.7. If you figure out how to fix it, I will bump the version and push it to pypi.

**Comment by Zeioth** [comment]
Travis doesn't seem to support python 3.7 yet. Temporary removed from .travis.yml. Everything should be fine now.

**Comment by Zeioth** [comment]
Version 1.2 is now available on Pypi.

**Comment by glowka** [comment]
Great!
Thanks for instant merge :)

**Pull request merged**
